definitions:
  model.ProgramRequest:
    properties:
      category_id:
        type: integer
      description:
        type: string
      name:
        type: string
      user_id:
        type: integer
    type: object
  model.ProgramResponse:
    properties:
      description:
        type: string
      id:
        type: integer
      name:
        type: string
    type: object
info:
  contact: {}
paths:
  /programs:
    post:
      consumes:
      - application/json
      description: Create a program
      parameters:
      - description: Program object that needs to be created
        in: body
        name: program
        required: true
        schema:
          $ref: '#/definitions/model.ProgramRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.ProgramResponse'
      summary: Create a program
      tags:
      - Program
swagger: "2.0"
